export const tableList = [
  //  {name: "SN"},{name: "Transaction ID"},{name: "Transactions Type"},{name: "Source Bank"},{name: "Source A/C Name"}, {name: "Destination Bank"}, {name: "Destination A/C Name"}, {name: "Account"}, {name: "Service Charge"},
  {
    id: 1,
    txnId: 1036,
    txnType: "coop t",
    sourceBank: "Mero Bank",
    sourceName: "Jojo",
    destinationBank: "ABC Saving & Cr",
    destinationName: "Joesph Joestar",
    account: "000122222260",
    serviceCharge: "Rs. 12",
  },
  {
    id: 2,
    txnId: 1036,
    txnType: "coop t",
    sourceBank: "Mero Bank",
    sourceName: "Jojo",
    destinationBank: "ABC Saving & Cr",
    destinationName: "Joesph Joestar",
    account: "000122222260",
    serviceCharge: "Rs. 12",
  },
  {
    id: 3,
    txnId: 1036,
    txnType: "coop t",
    sourceBank: "Mero Bank",
    sourceName: "Jojo",
    destinationBank: "ABC Saving & Cr",
    destinationName: "Joesph Joestar",
    account: "000122222260",
    serviceCharge: "Rs. 12",
  },
  {
    id: 4,
    txnId: 1036,
    txnType: "coop t",
    sourceBank: "Mero Bank",
    sourceName: "Jojo",
    destinationBank: "ABC Saving & Cr",
    destinationName: "Joesph Joestar",
    account: "000122222260",
    serviceCharge: "Rs. 12",
  },
];
